# Generated by Django 2.2.3 on 2019-07-24 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='num_ads',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='plan',
            name='days',
            field=models.IntegerField(default=0),
        ),
    ]
