# Generated by Django 2.2.3 on 2019-07-21 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_company_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='days',
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name='plan',
            name='name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='plan',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
